version: '3.2'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - ${HOST_PORT}:5432
    volumes:
      - postgres-pgdata:${PGDATA}
      - ${HOST_DB_INIT_SCRIPTS}:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
volumes:
  postgres-pgdata:
    driver: local
